# Generated by Django 5.2 on 2025-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_movie_watched_date_show_watched_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
